src/main/yj_memo

[YJ]commit test

---

src/main/webapp/YJ_Board/inputBoard.jsp
src/main/webapp/YJ_Board/viewBoard.jsp

[YJ] made Board

---

src/main/java/com/mj/festival/festivalHC.java
src/main/webapp/festival/festivalInfoBoard.jsp
src/main/webapp/index.jsp

[mj]데이터 테스트

---

src/main/webapp/DH_Slide/index.jsp
src/main/webapp/DH_Slide/index2.jsp
src/main/webapp/DH_Slide/test.jsp
src/main/webapp/dh_css/index.css

이미지 영역 표시만 하면 됨

---

.settings/org.eclipse.core.resources.prefs
src/main/java/com/mj/festival/FesDBManager.java
src/main/java/com/mj/festival/festival.java
src/main/java/com/mj/festival/festival.sql
src/main/java/com/mj/festival/festivalDAO.java
src/main/java/com/mj/festival/festivalHC.java
src/main/webapp/festival/index.jsp
src/main/webapp/festival/output.jsp
src/main/webapp/mj_fesInfo_board/mjIndex.jsp

2022.06.15 DB 생성 But 슬라이드와의 연동 실패

[mj] DB생성 But 슬라이드와 연동 실패

---

src/main/java/com/mj/festival/festivalDAO.java
src/main/java/com/mj/festival/festivalHC.java
src/main/java/com/mj/festival/festivalInfoCon.java
src/main/webapp/mj_fesInfo_board/css/component.css
src/main/webapp/mj_fesInfo_board/fesInfoBoard.jsp
src/main/webapp/mj_fesInfo_board/imgFromAddr.jsp
src/main/webapp/mj_fesInfo_board/index.html
src/main/webapp/mj_fesInfo_board/mjIndex.jsp
src/main/webapp/mj_fesInfo_board/seoulFestival/dobong.jsp
src/main/webapp/mj_fesInfo_board/seoulFestival/dongdaemoon.jsp
src/main/webapp/mj_fesInfo_board/seoulFestival/eunpyong.jsp
src/main/webapp/mj_fesInfo_board/seoulFestival/jongro.jsp
src/main/webapp/mj_fesInfo_board/seoulFestival/joonggu.jsp
src/main/webapp/mj_fesInfo_board/seoulFestival/joongranggu.jsp
src/main/webapp/mj_fesInfo_board/seoulFestival/kangbook.jsp
src/main/webapp/mj_fesInfo_board/seoulFestival/kangdong.jsp
src/main/webapp/mj_fesInfo_board/seoulFestival/kangnam.jsp
src/main/webapp/mj_fesInfo_board/seoulFestival/kumcheon.jsp
src/main/webapp/mj_fesInfo_board/seoulFestival/kwanak.jsp
src/main/webapp/mj_fesInfo_board/seoulFestival/kwangjin.jsp
src/main/webapp/mj_fesInfo_board/seoulFestival/mapo.jsp
src/main/webapp/mj_fesInfo_board/seoulFestival/nowon.jsp
src/main/webapp/mj_fesInfo_board/seoulFestival/seocho.jsp
src/main/webapp/mj_fesInfo_board/seoulFestival/seongbook.jsp
src/main/webapp/mj_fesInfo_board/seoulFestival/seongdong.jsp
src/main/webapp/mj_fesInfo_board/seoulFestival/songpa.jsp
src/main/webapp/mj_fesInfo_board/seoulFestival/yangcheon.jsp
src/main/webapp/mj_fesInfo_board/seoulFestival/yongsan.jsp

[mj] 슬라이드 수정 완료 & 사진 눌렀을 때 축제 정보 나오게끔 설정 완료

---

src/main/webapp/index.jsp
src/main/webapp/mj_fesInfo_board/mjIndex.jsp

[mj] 축제정보 카테고리에 festivalHC연결

---

src/main/java/com/mj/festival/festivalDAO.java
src/main/webapp/mj_fesInfo_board/css/fesInfoDeco.css
src/main/webapp/mj_fesInfo_board/css/festivalListDeco.css
src/main/webapp/mj_fesInfo_board/fesInfoBoard.jsp
src/main/webapp/mj_fesInfo_board/festivalList.jsp

[mj] 축제리스트 불러오기 성공, 이미지나 타이틀 누를 시 축제상세정보페이지로 이동 완료

---

src/main/webapp/SW_mapFolder/sw_map.jsp
src/main/webapp/SW_mapFolder/sw_map2.jsp

[sw] 지도 목록 표시 수정 +  jquery적용

---

src/main/java/com/sw/main/searchMapHC.java
src/main/webapp/SW_mapFolder/sw_map4.jsp
src/main/webapp/SW_mapFolder/sw_map5.jsp

[sw] 지도 수정

---

src/main/webapp/SW_mapFolder/sw_map3.jsp
src/main/webapp/SW_mapFolder/sw_map5.jsp
src/main/webapp/SW_mapFolder/sw_map_clusterer.jsp

[sw] map 클러스터 시도, 기존map살짝수정

---

src/main/java/com/mj/festival/FesDBManager.java
src/main/java/com/yj/main/DBManager.java
src/main/webapp/mj_calendar/php/month-view.html

[mj] 오라클 클라우드 연동 성공!

---

src/main/webapp/SW_mapFolder/sw_map4.jsp

[sw] 맵 크기 중심좌표 수정

---

src/main/java/com/t4/main/DBManager_Main.java
src/main/webapp/mj_fesInfo_board/imgFromAddr.jsp

[mj] 중간 커밋

---

src/main/webapp/home.jsp
src/main/webapp/mj_css/home.css

[mj] 메인 홈페이지 CSS 작업 완료

---

src/main/webapp/mj_fesInfo_board/css/festivalListDeco.css
src/main/webapp/mj_fesInfo_board/festivalList.jsp

[mj] fesInfoList css 작업 중

---

src/main/java/com/t4/main/DBManager_Main.java
src/main/java/com/t4/main/MainHC.java
src/main/java/com/yj/main/YJBoardDAO.java
src/main/webapp/home.jsp
src/main/webapp/mj_css/home.css
src/main/webapp/mj_fesInfo_board/css/fesInfoDeco.css

[Mj]메인 홈페이지에 탭 배너 CSS 

---

src/main/webapp/home.jsp
src/main/webapp/mj_css/home.css

[mj]푸터 위에 빈 공간 삽입

---

src/main/java/com/sw/main/searchMapHC.java
src/main/java/com/t4/main/DBManager_Main.java
src/main/webapp/SW_mapFolder/sw_map_final.jsp

[sw] map height수정

---

src/main/java/com/t4/main/DBManager_Main.java
src/main/webapp/home.jsp
src/main/webapp/mj_fesInfo_board/css/fesInfoDeco.css
src/main/webapp/mj_fesInfo_board/css/festivalListDeco.css
src/main/webapp/mj_fesInfo_board/fesInfoBoard.jsp

[mj] 축제상세정보페이지 CSS 구현

---

src/main/webapp/home.jsp

[mj] 캘린더 색상 변경

---

src/main/java/com/t4/main/DBManager_Main.java
src/main/webapp/home.jsp
src/main/webapp/mj_calendar/full_month.jsp
src/main/webapp/mj_calendar/month_view.jsp

[mj] calendar replace Link -> url

---

src/main/java/com/mj/festival/festivalDAO_JP.java
src/main/webapp/mj_fesInfo_board/imgFromAddr_JP.jsp

[mj]DAO에 jp 붙여서 수정

---

src/main/java/com/t4/main/DBManager_Main.java
src/main/webapp/YJ_Board/viewBoard.jsp
src/main/webapp/home.jsp
src/main/webapp/mj_calendar/full_month.jsp
src/main/webapp/mj_calendar/lib/main.css
src/main/webapp/mj_calendar/month_view.jsp
src/main/webapp/mj_fesInfo_board/mjIndex.jsp
src/main/webapp/yj_css/viewBoard.css

게시판 페이지 반응형 작업 완료!

---

src/main/webapp/mj_fesInfo_board/css/demo.css
src/main/webapp/mj_fesInfo_board/mjIndex.jsp

민지가 만든 슬라이드 페이지 반응형 작업 완료

---

src/main/java/com/mj_JP/festival/fesCalendarCon_jp.java
src/main/java/com/mj_JP/festival/festival.java
src/main/java/com/mj_JP/festival/festivalDAO_JP.java
src/main/java/com/mj_JP/festival/festivalHC_jp.java
src/main/java/com/mj_JP/festival/festivalInfoCon_jp.java
src/main/java/com/mj_JP/festival/festivalListCon_jp.java
src/main/java/com/t4/main/DBManager_Main.java
src/main/webapp/home_jp.jsp
src/main/webapp/mj_calendar/full_month_jp.jsp
src/main/webapp/mj_fesInfo_board/fesInfoBoard_jp.jsp
src/main/webapp/mj_fesInfo_board/festivalList_jp.jsp
src/main/webapp/mj_fesInfo_board/mjIndex_jp.jsp

[mj] 일본어 번역

---

src/main/webapp/mj_fesInfo_board/css/fesInfoDeco.css
src/main/webapp/mj_fesInfo_board/css/mjIndexDeco.css
src/main/webapp/mj_fesInfo_board/fesInfoBoard.jsp
src/main/webapp/mj_fesInfo_board/fesInfoBoard_jp.jsp
src/main/webapp/mj_fesInfo_board/mjIndex.jsp
src/main/webapp/mj_fesInfo_board/mjIndex_jp.jsp

[mj] 버튼 CSS디자인 수정 완료

---

src/main/java/com/mj/festival/festivalDAO.java
src/main/java/com/t4/main/DBManager_Main.java
src/main/webapp/home.jsp
src/main/webapp/mj_css/home.css
src/main/webapp/mj_fesInfo_board/imgFromAddr.jsp
src/main/webapp/mj_fesInfo_board/mjIndex.jsp

[mj] 필요없는 부분 삭제

---

src/main/webapp/mj_fesInfo_board/css/fesInfoDeco.css
src/main/webapp/mj_fesInfo_board/fesInfoBoard.jsp
src/main/webapp/mj_fesInfo_board/fesInfoBoard_jp.jsp

[mj] fesInfoBoard CSS 수정

---

src/main/webapp/home.jsp
src/main/webapp/mj_css/home.css

게시판과 캘린더를 모바일 화면 처럼 세로로 나열하는 건 실패😢

게시판 깨지는 거 해결

---

src/main/java/com/t4/main/DBManager_Main.java

[mj]pull을 위한 커밋

---

src/main/webapp/SW_mapFolder/sw_map_final_jp.jsp

[sw] 상세정보 넘기는 태그수정

---

src/main/webapp/home.jsp
src/main/webapp/mj_calendar/lib/main.css
src/main/webapp/mj_css/home.css
src/main/webapp/yj_css/index.css

[Dh] 엄청 힘냈음!!!!!!!!!!!!!!!!!!!!!!!

---

src/main/webapp/mj_css/home.css

안드로이드 호환 문제 해결

---

src/main/webapp/home.jsp
src/main/webapp/mj_css/home.css

맥 윈도우 호환문제 3트

---

src/main/webapp/mj_css/home.css
src/main/webapp/yj_css/index.css

반응형 적용 완료! (문제점 발견 되면 말씀주세요)

---

src/main/java/com/t4/main/DBManager_Main.java

[MJ] COMMIT FOR FULL
